### ISSUE TITLE
Broken on latest version of anki

### ISSUE THREAD

**Issue by kanjieater** [HelenFoster/KanjiVocab#15]
On the latest version of anki 2.1.21 and the latest beta 22, I'm seeing this error:
```
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-14 16:29:30
Caught exception:
Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Anki2\addons21\kanjivocab\__init__.py", line 17, in updateKanjiVocab
    from . import run
  File "C:\Users\AppData\Roaming\Anki2\addons21\kanjivocab\run.py", line 11, in <module>
    from anki.template import furigana
ImportError: cannot import name 'furigana' from 'anki.template' (C:\Program Files\Anki\anki\template.pyc)
```

**Comment by HelenFoster** [comment]
Thanks for letting me know. I'll look into it.
